# Generated by Django 2.2.5 on 2019-09-11 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pontoturistico_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturistico',
            name='atracoes',
        ),
        migrations.RemoveField(
            model_name='pontoturistico',
            name='avaliacoes',
        ),
        migrations.RemoveField(
            model_name='pontoturistico',
            name='comentarios',
        ),
    ]
