# Generated by Django 2.2.5 on 2019-09-11 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190911_0102'),
        ('atracoes', '0002_atracao_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='ponto_turistico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.PontoTuristico'),
            preserve_default=False,
        ),
    ]
